apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dealership
  template:
    metadata:
      labels:
        app: dealership
    spec:
      containers:
        - name: dealership
          image: dealership:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: backend_url
              value: "http://host.docker.internal:3030"
            - name: sentiment_analyzer_url
              value: "http://host.docker.internal:5050"
            - name: searchcars_url
              value: "http://host.docker.internal:3050"
          readinessProbe:
            httpGet:
              path: /login/
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 5
            periodSeconds: 5
